### ISSUE TITLE
heya

### ISSUE THREAD

**Issue by katieannemills** [remi-daigle/studyGroup#1]
Hi Remi - thanks for getting this set up! Are you at Acadia now? Let me know anything I can do to help, and when you have your first event set up I'll add you to the Study Group map and let everyone know!

**Comment by remi-daigle** [comment]
I'm not there yet, flying out on the 31st. I'm just getting things started before the move. It sounds like there is enough interest for a SWC workshop and the idea is to run that early in the semester to get the grad students 'on the right track'. We could then plug the study group at the workshop and kick it off afterwards. I will let you know when we have things scheduled! Thanks for the help!

**Comment by katieannemills** [comment]
That sounds like an awesome plan! Let me know anything you need.

**Comment by remi-daigle** [comment]
OK, full disclosure, much of how the inner workings of the website is currently a little above my head, but I'm keen to learn. I just git jekyll working on my Windows machine today and I can now test things without having to commit to github and waiting. 

One thing I'd like to change is to have the location/date/time on a separate line like the SFU group has done. I find it easier to read. I perused the commits on @ttimbers 's repo, but I couldn't identify where that change was made.

**Comment by katieannemills** [comment]
No problem, jekyll definitely takes some getting used to! I think you're looking for [this commit](https://github.com/ttimbers/studyGroup/commit/2a514ba24dd7fe298bf584d36b44a3ebaaa790ed); in general, if you're looking for layout stuff, it's all in `_includes`, and if you're looking for commits where people did stuff, I like to go to the relevant file and use the 'history' button - that'll get you the commit you want with the least pain (assuming the commit messages are something useful). Let me know if I can help!

**Comment by remi-daigle** [comment]
So easy when you know!! Thanks, that worked like a charm!

**Comment by remi-daigle** [comment]
Hey @BillMills, I just posted our first event, it's going to be before the SWC workshop, but right after an R introductory session (similar to what would be covered for R in SWC). We're still going to run the SWC workshop, but in mid October

**Comment by katieannemills** [comment]
Nice - you're [on the map](https://github.com/mozillascience/studyGroupLessons/blob/master/whereWeAre.geojson)! Let me know how those first sessions go, and do please report back on any lesson notes or webcasts you make so we can share them back. Also, did I mention the [mailing list](https://mail.mozilla.org/listinfo/msl-study-groups) to you yet? We're using this list to organize communication and meetings between all the Study Group leads. Jump in there too!
