### ISSUE TITLE
Resampling Algorithms for Sensitivity Analyses

### ISSUE THREAD

**Issue by DanielleQuinn** [remi-daigle/studyGroup#10]
Ecological studies often suffer from limited resource availability, including time, money, and people power. Oversampling not only taxes these resources needlessly, but may also negatively influence the system being studied; for example, through lethal collections of organisms or unnecessary handling of non-target species. Projects relying on data collection over multiple field seasons may benefit from resampling algorithms that can identify efficient collection protocols if oversampling is known or thought to have occurred.

We'll be using a mock data set of tagged and non-tagged eels captured in a small lake to estimate population size, then build a resampling algorithm to explore the sensitivity of using varying numbers of traps and sampling events.

**Where:** The U-Club, Acadia University
**When:** November 6, 2:00 PM

**Public Notepad:** [Etherpad](https://public.etherpad-mozilla.org/p/SensitivityAnalysis_DQ)
**Lesson Material:** [Notes](http://daniellequinn.github.io/RLessons/SensitivityAnalysis/SensitivityAnalysis.html), [Data](https://github.com/DanielleQuinn/RLessons/blob/master/SensitivityAnalysis/recapture_data.csv), [Code Along](https://github.com/DanielleQuinn/RLessons/blob/master/SensitivityAnalysis/SensitivityAnalysis_NoCode.R), [Raw Data](https://raw.githubusercontent.com/DanielleQuinn/RLessons/master/SensitivityAnalysis/recapture_data.csv)

**Prerequisite knowledge:** None
**Dependencies:** R, (and Rstudio)
**Required packages:** dplyr, FSA, lubridate, ggplot2, digest

**Comment by remi-daigle** [comment]
Yeah! I'm looking forward to this!
